### PR TITLE
Broadcast between LArray and Array 

### LINKED ISSUE #25: Broadcast error for `LArray`s of different types
On master:

```julia
julia> using LabelledArrays

julia> x = @LArray [1, 2] (:a, :b)
2-element LArray{Int64,1,(:a, :b)}:
 1
 2

julia> y = Float64.(x)
2-element LArray{Float64,1,(:a, :b)}:
 1.0
 2.0

julia> x .+ y
ERROR: conflicting broadcast rules defined
  Broadcast.BroadcastStyle(::LabelledArrays.LAStyle{Float64,1,(:a, :b)}, ::LabelledArrays.LAStyle{Int64,1,(:a, :b)}) = LabelledArrays.LAStyle{Float64,1,(:a, :b)}()
  Broadcast.BroadcastStyle(::LabelledArrays.LAStyle{Int64,1,(:a, :b)}, ::LabelledArrays.LAStyle{Float64,1,(:a, :b)}) = LabelledArrays.LAStyle{Int64,1,(:a, :b)}()
One of these should be undefined (and thus return Broadcast.Unknown).
```

`SVector` is fine:

```julia
julia> AB = @SLVector (:a,:b)
SLArray{Tuple{2},1,(:a, :b),T} where T

julia> x = AB(1,2)
2-element SLArray{Tuple{2},1,(:a, :b),Int64}:
 1
 2

julia> y = Float64.(x)
2-element SLArray{Tuple{2},1,(:a, :b),Float64}:
 1.0
 2.0

julia> x .+ y
2-element SLArray{Tuple{2},1,(:a, :b),Float64}:
 2.0
 4.0
```

### PR DESCRIPTION
**Pull request by YingboMa**
Fixes #25

### CODE REVIEW

File: test/larrays.jl [hunk 1]
```diff
@@ -27,10 +27,12 @@ g(x) = x.a
...
 x = @LArray [1,2,3] (:a,:b,:c)
-x .* x isa LArray
-x .+ 1 isa LArray
-x .+ 1. isa LArray
-eltype(x .+ 1.) === Float64
+@test x .* x isa LArray
+@test x .+ 1 isa LArray
+@test x .+ 1. isa LArray
+z = x .+ ones(Int, 3)
+@test z isa LArray && eltype(z) === Int
```
Comment (MSeeker1340) [inline test/larrays.jl]: For the purpose of regression test, I think it's better to use mixed precision here
```julia
z = x .+ ones(Float64, 2)
@test z isa LArray && eltype(z) === Float64
```
